name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: safeescape
  SERVICE_NAME: safescape-backend
  REGION: asia-south1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: safescape-backend
          region: asia-south1
          source: ./
          