name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: safeescape
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    
    - name: Authorize Docker push
      run: gcloud auth configure-docker asia-south1-docker.pkg.dev
    
    - name: Build and push
      run: |
        docker build -t asia-south1-docker.pkg.dev/safeescape/cloud-run-source-deploy/safescape-backend:${{ github.sha }} .
        docker push asia-south1-docker.pkg.dev/safeescape/cloud-run-source-deploy/safescape-backend:${{ github.sha }}
      
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy safescape-backend \
          --image asia-south1-docker.pkg.dev/safeescape/cloud-run-source-deploy/safescape-backend:${{ github.sha }} \
          --platform managed \
          --region asia-south1 \
          --allow-unauthenticated \
          --set-env-vars="NODE_ENV=production,GOOGLE_CLOUD_PROJECT=safeescape" \
          --set-secrets="FIREBASE_CREDENTIALS=firebase-credentials:latest,VERTEXAI_CREDENTIALS=vertexai-credentials:latest,OPENWEATHER_API_KEY=openweather-api-key:latest"