name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    
    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        install_components: 'gke-gcloud-auth-plugin'
    
    - name: Configure Docker for Artifact Registry
      run: |
        gcloud --quiet auth configure-docker asia-south1-docker.pkg.dev
        # Validate authentication
        gcloud auth list
        gcloud config list
    
    - name: Build and push Docker image
      run: |
        # Build the Docker image
        docker build -t asia-south1-docker.pkg.dev/safeescape/cloud-run-source-deploy/safescape-backend:${{ github.sha }} .
        # Push the Docker image
        docker push asia-south1-docker.pkg.dev/safeescape/cloud-run-source-deploy/safescape-backend:${{ github.sha }}
      
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy safescape-backend \
          --image asia-south1-docker.pkg.dev/safeescape/cloud-run-source-deploy/safescape-backend:${{ github.sha }} \
          --platform managed \
          --region asia-south1 \
          --allow-unauthenticated \
          --set-env-vars="NODE_ENV=production,GOOGLE_CLOUD_PROJECT=safeescape" \
          --set-secrets="FIREBASE_CREDENTIALS=firebase-credentials:latest,VERTEXAI_CREDENTIALS=vertexai-credentials:latest,OPENWEATHER_API_KEY=openweather-api-key:latest"